In [123]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [124]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [125]:
data.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [126]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [127]:
#encode categorical data
le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])

In [128]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [129]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
data2 = ohe.fit_transform(data[['Geography']])
data2

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [130]:
ohe.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [131]:
data2.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [132]:
encoded_df=pd.DataFrame(data2.toarray(),columns=ohe.get_feature_names_out(['Geography']))

In [133]:
encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [134]:
data=pd.DataFrame(data)
data=pd.concat([data,encoded_df],axis=1)

In [135]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,France,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,France,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [136]:
data.drop('Geography',axis=1,inplace=True)

In [137]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [138]:
#save encoder and scaler
with open('label_encoder.pkl','wb') as f:
    pickle.dump(le,f)

with open('onehot_encoder.pkl','wb') as f:
    pickle.dump(ohe,f)

In [139]:
X=data.drop('Exited',axis=1)
y=data['Exited']

In [182]:
X.columns

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Geography_France',
       'Geography_Germany', 'Geography_Spain'],
      dtype='str')

In [185]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [140]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [141]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [142]:
X_train_scaled

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 12))

In [143]:
X_test_scaled

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(2000, 12))

In [144]:
with open('scaler.pkl','wb') as f:
    pickle.dump(scaler,f)

In [145]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [146]:
(X_train_scaled.shape[1],)

(12,)

In [147]:
##building the model
model=Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),# HL1
    Dense(32, activation='relu'),# HL2
    Dense(1, activation='sigmoid')# Output layer
    ]
)

c:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [148]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [149]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.001)
loss_fn=tensorflow.keras.losses.BinaryCrossentropy()

In [150]:
import tensorflow as tf

print(tf.__version__)
print("GPUs:", tf.config.list_physical_devices('GPU'))

2.21.0
GPUs: []

In [151]:
!pip install tensorflow==2.10

WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.10 (from versions: 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0, 2.15.1, 2.16.0rc0, 2.16.1, 2.16.2, 2.17.0rc0, 2.17.0rc1, 2.17.0, 2.17.1, 2.18.0rc0, 2.18.0rc1, 2.18.0rc2, 2.18.0, 2.18.1, 2.19.0rc0, 2.19.0, 2.19.1, 2.20.0rc0, 2.20.0, 2.21.0rc0, 2.21.0rc1, 2.21.0)
ERROR: No matching distribution found for tensorflow==2.10

In [152]:
#compile the model
model.compile(optimizer=opt,loss=loss_fn,metrics=['accuracy'])

In [153]:
#tensorboard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [154]:
#setup early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [155]:
#train the model
history = model.fit(X_train_scaled, y_train, epochs=100, batch_size=32, validation_split=0.2, callbacks=[early_stopping, tensorboard_callback])

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.7891 - loss: 0.4726 - val_accuracy: 0.8288 - val_loss: 0.4023
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8333 - loss: 0.3962 - val_accuracy: 0.8481 - val_loss: 0.3704
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8548 - loss: 0.3624 - val_accuracy: 0.8556 - val_loss: 0.3559
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8552 - loss: 0.3484 - val_accuracy: 0.8550 - val_loss: 0.3486
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8577 - loss: 0.3424 - val_accuracy: 0.8594 - val_loss: 0.3438
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8631 - loss: 0.3366 - val_accuracy: 0.8475 - val_loss: 0.3475
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8603 - loss: 0.3349 - val_accuracy: 0.8544 - val_loss: 0.3425
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8642 - loss: 0.3312 - val_accuracy: 0.8519 - val_loss: 0.3429
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8653 - loss: 0.3290 - val_accuracy: 0.8569 - val_loss: 0.3414
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8645 - loss: 0.3263 - val_accuracy: 0.8519 - val_loss: 0.3420
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8666 - loss: 0.3234 - val_accuracy: 0.8506 - val_loss: 0.3411
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8677 - loss: 0.3203 - val_accuracy: 0.8512 - val_loss: 0.3411
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8698 - loss: 0.3189 - val_accuracy: 0.8519 - val_loss: 0.3440
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8678 - loss: 0.3179 - val_accuracy: 0.8519 - val_loss: 0.3387
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8687 - loss: 0.3140 - val_accuracy: 0.8537 - val_loss: 0.3440
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8692 - loss: 0.3128 - val_accuracy: 0.8556 - val_loss: 0.3381
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8731 - loss: 0.3123 - val_accuracy: 0.8537 - val_loss: 0.3396
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8698 - loss: 0.3090 - val_accuracy: 0.8475 - val_loss: 0.3438
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8711 - loss: 0.3086 - val_accuracy: 0.8494 - val_loss: 0.3443
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8719 - loss: 0.3068 - val_accuracy: 0.8500 - val_loss: 0.3425
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8744 - loss: 0.3069 - val_accuracy: 0.8494 - val_loss: 0.3435

In [156]:
model.save('churn_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [157]:
#load tensorboard extension
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [158]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [159]:
!pip install --upgrade setuptools

Requirement already satisfied: setuptools in .\venv1\Lib\site-packages (75.8.0)
Collecting setuptools
  Using cached setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Using cached setuptools-82.0.1-py3-none-any.whl (1.0 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.8.0
    Uninstalling setuptools-75.8.0:
      Successfully uninstalled setuptools-75.8.0
Successfully installed setuptools-82.0.1

WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)

In [160]:
import pip
!pip uninstall tensorboard -y
!pip install tensorboard

WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Skipping tensorboard as it is not installed.

Collecting tensorboard
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: absl-py>=0.4 in .\venv1\Lib\site-packages (from tensorboard) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in .\venv1\Lib\site-packages (from tensorboard) (1.81.1)
Requirement already satisfied: markdown>=2.6.8 in .\venv1\Lib\site-packages (from tensorboard) (3.10.2)
Requirement already satisfied: numpy>=1.12.0 in .\venv1\Lib\site-packages (from tensorboard) (2.4.6)
Requirement already satisfied: packaging in .\venv1\Lib\site-packages (from tensorboard) (26.0)
Requirement already satisfied: pillow in .\venv1\Lib\site-packages (from tensorboard) (12.2.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in .\venv1\Lib\site-packages (from tensorboard) (7.35.1)
Requirement already satisfied: setuptools>=41.0.0 in .\venv1\Lib\site-packages (from tensorboard) (82.0.1)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv1\Lib\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in .\venv1\Lib\site-packages (from grpcio>=1.48.2->tensorboard) (4.15.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv1\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Using cached tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
Using cached tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Installing collected packages: tensorboard-data-server, tensorboard

   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]

WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
  WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Lenovo\\Desktop\\DeepLearning\\venv1\\Scripts\\tensorboard.exe' -> 'C:\\Users\\Lenovo\\Desktop\\DeepLearning\\venv1\\Scripts\\tensorboard.exe.deleteme'
Consider using the `--user` option or check the permissions.

In [161]:
!pip install pkg_resources

WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
ERROR: Could not find a version that satisfies the requirement pkg_resources (from versions: none)
ERROR: No matching distribution found for pkg_resources

In [162]:
%pip install "setuptools<81" --force-reinstall

Collecting setuptools<81
  Using cached setuptools-80.10.2-py3-none-any.whl.metadata (6.6 kB)
Using cached setuptools-80.10.2-py3-none-any.whl (1.1 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 82.0.1
    Uninstalling setuptools-82.0.1:
      Successfully uninstalled setuptools-82.0.1
Successfully installed setuptools-80.10.2
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ (c:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (c:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (c:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (c:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (c:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (c:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)

In [163]:
!python -c "import pkg_resources; print('working')"

working

<string>:1: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.

In [164]:
!python -c "import setuptools; print(setuptools.__version__)"

80.10.2

In [165]:
!python -c "import setuptools; print(setuptools.__file__)"

c:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\setuptools\__init__.py

In [166]:
!python -c "from setuptools import pkg_resources"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'pkg_resources' from 'setuptools' (c:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\setuptools\__init__.py)

In [167]:
!pip uninstall setuptools -y
!pip install setuptools==75.8.0

Found existing installation: setuptools 80.10.2
Uninstalling setuptools-80.10.2:
  Successfully uninstalled setuptools-80.10.2
Collecting setuptools==75.8.0
  Using cached setuptools-75.8.0-py3-none-any.whl.metadata (6.7 kB)
Using cached setuptools-75.8.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools
Successfully installed setuptools-75.8.0

WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)

In [168]:
!python -c "import pkg_resources; print(pkg_resources.__file__)"

c:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\pkg_resources\__init__.py

<string>:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

In [169]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [170]:
%reload_ext tensorboard

In [171]:
%tensorboard --logdir logs/fit20260618-223336

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1781802633.863548   15308 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1781802639.127227   15308 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\tensorboard\main.py", line 41, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\absl\app.py", line 367, in run
    _run_main(main, args)
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\absl\app.py", line 312, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\tensorboard\program.py", line 278, in main
    return runner(self.flags) or 0
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\tensorboard\program.py", line 294, in _run_serve_subcommand
    server = self._make_server()
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\tensorboard\program.py", line 469, in _make_server
    app = application.TensorBoardWSGIApp(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\tensorboard\backend\application.py", line 139, in TensorBoardWSGIApp
    return TensorBoardWSGI(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\tensorboard\backend\application.py", line 252, in __init__
    raise ValueError(
ValueError: Duplicate plugins for name projector

In [172]:
import os

for root, dirs, files in os.walk("logs"):
    for f in files:
        print(os.path.join(root, f))

logs\fit\20260618-223336\train\events.out.tfevents.1781802217.DESKTOP-BM53IAU.1192.2.v2
logs\fit\20260618-223336\validation\events.out.tfevents.1781802220.DESKTOP-BM53IAU.1192.3.v2
logs\fit\20260618-223940\train\events.out.tfevents.1781802580.DESKTOP-BM53IAU.1192.4.v2
logs\fit\20260618-223940\validation\events.out.tfevents.1781802583.DESKTOP-BM53IAU.1192.5.v2

In [173]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [174]:
%reload_ext tensorboard

In [175]:
!pip list | findstr tensor

tensorboard               2.20.0
tensorboard-data-server   0.7.2
tensorflow                2.21.0

WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)

In [176]:
!pip uninstall tensorboard -y
!pip uninstall tensorboard-data-server -y

Found existing installation: tensorboard 2.20.0
Uninstalling tensorboard-2.20.0:

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\shutil.py", line 853, in move
    os.rename(src, real_dst)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\users\\lenovo\\desktop\\deeplearning\\venv1\\scripts\\tensorboard.exe' -> 'C:\\Users\\Lenovo\\AppData\\Local\\Temp\\pip-uninstall-qc5wvnn6\\tensorboard.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\pip\_internal\cli\base_command.py", line 109, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\pip\_internal\cli\base_command.py", line 102, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\pip\_internal\commands\uninstall.py", line 105, in run
    uninstall_pathset = req.uninstall(
                        ^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\pip\_internal\req\req_install.py", line 685, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\pip\_internal\req\req_uninstall.py", line 373, in remove
    moved.stash(path)
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\pip\_internal\req\req_uninstall.py", line 264, in stash
    renames(path, new_path)
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\pip\_internal\utils\misc.py", line 344, in renames
    shutil.move(old, new)
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\shutil.py", line 874, in move
    os.unlink(src)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\users\\lenovo\\desktop\\deeplearning\\venv1\\scripts\\tensorboard.exe'

Found existing installation: tensorboard-data-server 0.7.2
Uninstalling tensorboard-data-server-0.7.2:
  Successfully uninstalled tensorboard-data-server-0.7.2

In [177]:
!pip list | findstr tensor

tensorflow                2.21.0

WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~~nsorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)

In [180]:
!pip install tensorboard

Collecting tensorboard
  Using cached tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: absl-py>=0.4 in .\venv1\Lib\site-packages (from tensorboard) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in .\venv1\Lib\site-packages (from tensorboard) (1.81.1)
Requirement already satisfied: markdown>=2.6.8 in .\venv1\Lib\site-packages (from tensorboard) (3.10.2)
Requirement already satisfied: numpy>=1.12.0 in .\venv1\Lib\site-packages (from tensorboard) (2.4.6)
Requirement already satisfied: packaging in .\venv1\Lib\site-packages (from tensorboard) (26.0)
Requirement already satisfied: pillow in .\venv1\Lib\site-packages (from tensorboard) (12.2.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in .\venv1\Lib\site-packages (from tensorboard) (7.35.1)
Requirement already satisfied: setuptools>=41.0.0 in .\venv1\Lib\site-packages (from tensorboard) (75.8.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard)
  Using cached tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv1\Lib\site-packages (from tensorboard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in .\venv1\Lib\site-packages (from grpcio>=1.48.2->tensorboard) (4.15.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv1\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Using cached tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
Using cached tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Installing collected packages: tensorboard-data-server, tensorboard

   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]
   -------------------- ------------------- 1/2 [tensorboard]

WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~~nsorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ensorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
WARNING: Ignoring invalid distribution ~~nsorboard (C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages)
  WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Lenovo\\Desktop\\DeepLearning\\venv1\\Scripts\\tensorboard.exe' -> 'C:\\Users\\Lenovo\\Desktop\\DeepLearning\\venv1\\Scripts\\tensorboard.exe.deleteme'
Consider using the `--user` option or check the permissions.

In [181]:
%tensorboard --logdir logs/fit20260618-223940

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1781802746.661949    7684 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1781802751.162450    7684 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\tensorboard\main.py", line 41, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\absl\app.py", line 367, in run
    _run_main(main, args)
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\absl\app.py", line 312, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\tensorboard\program.py", line 278, in main
    return runner(self.flags) or 0
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\tensorboard\program.py", line 294, in _run_serve_subcommand
    server = self._make_server()
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\tensorboard\program.py", line 469, in _make_server
    app = application.TensorBoardWSGIApp(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\tensorboard\backend\application.py", line 139, in TensorBoardWSGIApp
    return TensorBoardWSGI(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\tensorboard\backend\application.py", line 252, in __init__
    raise ValueError(
ValueError: Duplicate plugins for name projector