In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle
from tensorflow.keras.models import load_model

In [29]:
model=load_model('churn_model.h5')

with open('scaler.pkl','rb') as f:
    scaler=pickle.load(f)
with open('label_encoder.pkl','rb') as f:
    le=pickle.load(f)
with open('onehot_encoder.pkl','rb') as f:
    one_hot_encoder=pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [30]:
input_data = {
    'creditScore': 600,
    'geography': "France",
    'gender': "Male",
    'age': 40,
    'tenure': 3,
    'balance': 60000,
    'numOfProducts': 2,
    'hasCrCard': 1,
    'isActiveMember': 1,
    'estimatedSalary': 50000
}

In [31]:
# Geography Encoding (OneHotEncoder)
geo_encoded = one_hot_encoder.transform(
    [[input_data['geography']]]
).toarray()

geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns=one_hot_encoder.get_feature_names_out(['Geography'])
)

# Gender Encoding (LabelEncoder)
gender_encoded = le.transform(
    [input_data['gender']]
)[0]

c:\Users\Lenovo\Desktop\DeepLearning\venv1\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [32]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [33]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [40]:
input_df = pd.DataFrame({
    'CreditScore': [input_data['creditScore']],
    'Gender': [gender_encoded],
    'Age': [input_data['age']],
    'Tenure': [input_data['tenure']],
    'Balance': [input_data['balance']],
    'NumOfProducts': [input_data['numOfProducts']],
    'HasCrCard': [input_data['hasCrCard']],
    'IsActiveMember': [input_data['isActiveMember']],
    'EstimatedSalary': [input_data['estimatedSalary']]
})

In [41]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,1,40,3,60000,2,1,1,50000

In [ ]:
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [ ]:
prediction = model.predict(input_scaled)
prediction
prediction_proba = prediction[0][0]

print("Churn Probability:", prediction_proba)

if prediction_proba > 0.5:
    print("Customer is likely to churn")
else:
    print("Customer is not likely to churn")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
Churn Probability: 0.030858643
Customer is not likely to churn